### ISSUE TITLE
lose some dll and lib~

### ISSUE THREAD

**Issue by buaaCCJ** [VRGroupRWTH/VTKPlugin#1]
lose some dll and lib~

**Comment by acdemiralp** [comment]
Hey, I am assuming there are linking errors, are you on Linux, Mac or Windows?

**Comment by buaaCCJ** [comment]
I use install_vtk.bat to build vtk and it works. However with this libs, When I use vtkPolyDataReader to read .vtk file, I got some errors like: unresolved external symbol: vtkPolyDataReader . Have you guys used this library to read vtk files locally in Unreal? Need some help~ Thanks!

**Comment by acdemiralp** [comment]
I did and have used it to load vtkPolyData in another plugin, but that was some time ago. 

Can you confirm that the headers and libraries are created correctly in:
```
..\..\Source\ThirdParty\VTK\Public\
..\..\Intermediate\ThirdParty\VTK\Win64\
..\..\Binaries\ThirdParty\VTK\Win64\
```
If this is not the issue, then the UE build variables in https://github.com/VRGroupRWTH/VTKPlugin/blob/main/Source/ThirdParty/VTK/VTK.Build.cs might have changed between versions.

Please give me some time, I will install UE and take a look at what is going on. If you have the full error log, I might be able to help faster.

**Comment by jfmilke** [comment]
Changed the plugin structure and solved linker issues.
